version: '3.8'

services:
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    depends_on:
      - mongo

  db:
    build: db
    depends_on:
      - redis
      - mongo

  api:
    build: api
    ports:
      - "8000:80"
    depends_on:
      - db

  website:
    build: site
    ports:
      - "80:80"
    depends_on:
      - api

  tgbot:
    build: bot
    depends_on:
      - website


volumes:
  mongo-data:
