version: '3.8'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  db:
    build: db
    ports:
      - "9090:80"
    depends_on:
      - redis
      - mongo

  api:
    build: api
    ports:
      - "8000:80"
    depends_on:
      - db

volumes:
  mongo-data:
