version: '3.8'

services:
  mongo:
    image: "mongo:latest"
    volumes:
      - mongo-data:/data/db

  redis:
    image: "redis:latest"
    depends_on:
      - mongo

  payment-code-redis:
    image: "redis:latest"

  payment-request-redis:
    image: "redis:latest"

  payment-processor:
    build: paymentprocessor

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq



  codeservice:
    build: codeservice
    depends_on:
      - payment-code-redis
      - rabbitmq
    ports:
      - "90:80"

  waiting_queue_money_transfer:
    build: WaitingQueueMoneyTransfer

  paymentprocessor:
    build: paymentprocessor
    depends_on:
      - rabbitmq

  notificator:
    build: notificator


  db:
    build: db
    depends_on:
      - redis
      - mongo

  api:
    build: api
    ports:
      - "8000:80"
    depends_on:
      - db

  website:
    build: site
    ports:
      - "80:80"
    depends_on:
      - api

  tgbot:
    build: bot
    depends_on:
      - website


volumes:
  mongo-data:
  rabbitmq_data:
