version: '1.0'


services:
  dbserver:
    build: ./db
    container_name: dbserver
    ports:
      - "5040:5040"
    depends_on:
      - redis
      - mongodb

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor